/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.6
 * Generated at: 2025-08-17 03:56:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class EmployeeAddForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/mytags/tmtags.tld", Long.valueOf(1754657472219L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fEntityList_0026_005fpopulatorMethod_005fpopulatorClass_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftm_005fEntityList_0026_005fpopulatorMethod_005fpopulatorClass_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.release();
    _005fjspx_005ftagPool_005ftm_005fEntityList_0026_005fpopulatorMethod_005fpopulatorClass_005fname.release();
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fModule_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      com.thinking.machines.hr.beans.EmployeeBean employeeBean = null;
      employeeBean = (com.thinking.machines.hr.beans.EmployeeBean) _jspx_page_context.getAttribute("employeeBean", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (employeeBean == null){
        employeeBean = new com.thinking.machines.hr.beans.EmployeeBean();
        _jspx_page_context.setAttribute("employeeBean", employeeBean, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.thinking.machines.hr.beans.EmployeeErrorBean employeeErrorBean = null;
      employeeErrorBean = (com.thinking.machines.hr.beans.EmployeeErrorBean) _jspx_page_context.getAttribute("employeeErrorBean", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (employeeErrorBean == null){
        employeeErrorBean = new com.thinking.machines.hr.beans.EmployeeErrorBean();
        _jspx_page_context.setAttribute("employeeErrorBean", employeeErrorBean, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/MasterPageTopSection.jsp", out, false);
      out.write("\r\n");
      out.write("<script src='/styletwo/js/EmployeeAddForm.js'></script>\r\n");
      out.write("<h2>Employee (Add Module)</h2><br>\r\n");
      out.write("<form method='post' action='/styletwo/AddEmployee.jsp' onsubmit='return validateForm(this)'>\r\n");
      if (_jspx_meth_tm_005fFormId_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Name</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type='text' id='name' name='name' maxlength='35' size='36' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("<span id='nameErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Designation</td>\r\n");
      out.write("<td>\r\n");
      out.write("<select id='designationCode' name='designationCode'>\r\n");
      out.write("<option value='-1'>&lt;Select Designation&gt;</option>\r\n");
      if (_jspx_meth_tm_005fEntityList_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<span id='designationCodeErrorSection' style='color:red'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeErrorBean.designationCodeError}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Date of birth</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type='date' id='dateOfBirth' name='dateOfBirth' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.dateOfBirth}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>	\r\n");
      out.write("<span id='dateOfBirthErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Gender</td>\r\n");
      if (_jspx_meth_tm_005fIf_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fIf_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      if (_jspx_meth_tm_005fIf_005f4(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fIf_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<span id='genderErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Indian?</td>\r\n");
      out.write("<td>\r\n");
      if (_jspx_meth_tm_005fIf_005f6(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fIf_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<span id='isIndianErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Basic salary</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type='text' id='basicSalary' name='basicSalary' maxlength='11' size='13' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.basicSalary}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' style='text-align:right'>\r\n");
      out.write("<span id='basicSalaryErrorSection' style='color:red'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeErrorBean.basicSalaryError}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>PAN number</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type='text' id='panNumber' name='panNumber' maxlength='15' size='16' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.panNumber}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("<span id='panNumberErrorSection' style='color:red'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeErrorBean.panNumberError}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Aadhar Card Number</td>\r\n");
      out.write("<td>\r\n");
      out.write("<input type='text' id='aadharCardNumber' name='aadharCardNumber' maxlength='15' size='16' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.aadharCardNumber}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("<span id='aadharCardNumberErrorSection' style='color:red'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeErrorBean.aadharCardNumberError}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<span id='errorSection' style='color:red'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorBean.error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("<br><br>\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button type='submit'>Add</button>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button type='button' onclick='cancelEmployeeAddition()'>Cancel</button>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<form action='/styletwo/Employees.jsp' id='cancelEmployeeAdditionForm'>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/MasterPageBottomSection.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tm_005fModule_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  tm:Module
    com.thinking.machines.hr.tags.ModuleTagHandler _jspx_th_tm_005fModule_005f0 = (com.thinking.machines.hr.tags.ModuleTagHandler) _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.get(com.thinking.machines.hr.tags.ModuleTagHandler.class);
    _jspx_th_tm_005fModule_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fModule_005f0.setParent(null);
    // /EmployeeAddForm.jsp(2,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fModule_005f0.setName("EMPLOYEE");
    int _jspx_eval_tm_005fModule_005f0 = _jspx_th_tm_005fModule_005f0.doStartTag();
    if (_jspx_th_tm_005fModule_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.reuse(_jspx_th_tm_005fModule_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fFormId_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  tm:FormId
    com.thinking.machines.hr.tags.FormIdTagHandler _jspx_th_tm_005fFormId_005f0 = (com.thinking.machines.hr.tags.FormIdTagHandler) _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.get(com.thinking.machines.hr.tags.FormIdTagHandler.class);
    _jspx_th_tm_005fFormId_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fFormId_005f0.setParent(null);
    int _jspx_eval_tm_005fFormId_005f0 = _jspx_th_tm_005fFormId_005f0.doStartTag();
    if (_jspx_th_tm_005fFormId_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.reuse(_jspx_th_tm_005fFormId_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fEntityList_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:EntityList
    com.thinking.machines.hr.tags.EntityListTagHandler _jspx_th_tm_005fEntityList_005f0 = (com.thinking.machines.hr.tags.EntityListTagHandler) _005fjspx_005ftagPool_005ftm_005fEntityList_0026_005fpopulatorMethod_005fpopulatorClass_005fname.get(com.thinking.machines.hr.tags.EntityListTagHandler.class);
    _jspx_th_tm_005fEntityList_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fEntityList_005f0.setParent(null);
    // /EmployeeAddForm.jsp(23,0) name = populatorClass type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fEntityList_005f0.setPopulatorClass("com.thinking.machines.hr.bl.DesignationBL");
    // /EmployeeAddForm.jsp(23,0) name = populatorMethod type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fEntityList_005f0.setPopulatorMethod("getAll");
    // /EmployeeAddForm.jsp(23,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fEntityList_005f0.setName("designation");
    int _jspx_eval_tm_005fEntityList_005f0 = _jspx_th_tm_005fEntityList_005f0.doStartTag();
    if (_jspx_eval_tm_005fEntityList_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_tm_005fEntityList_005f0 != jakarta.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tm_005fEntityList_005f0);
      }
      do {
        out.write('\r');
        out.write('\n');
        if (_jspx_meth_tm_005fIf_005f0(_jspx_th_tm_005fEntityList_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        if (_jspx_meth_tm_005fIf_005f1(_jspx_th_tm_005fEntityList_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_tm_005fEntityList_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_tm_005fEntityList_005f0 != jakarta.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_tm_005fEntityList_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fEntityList_0026_005fpopulatorMethod_005fpopulatorClass_005fname.reuse(_jspx_th_tm_005fEntityList_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_tm_005fEntityList_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f0 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_tm_005fEntityList_005f0);
    // /EmployeeAddForm.jsp(24,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f0.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.designationCode==designation.code}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f0 = _jspx_th_tm_005fIf_005f0.doStartTag();
    if (_jspx_eval_tm_005fIf_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<option selected value='");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designation.code}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('\'');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designation.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_tm_005fEntityList_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f1 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_tm_005fEntityList_005f0);
    // /EmployeeAddForm.jsp(27,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f1.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.designationCode!=designation.code}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f1 = _jspx_th_tm_005fIf_005f1.doStartTag();
    if (_jspx_eval_tm_005fIf_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<option value='");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designation.code}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('\'');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${designation.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f1);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f2 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f2.setParent(null);
    // /EmployeeAddForm.jsp(45,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f2.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.male}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f2 = _jspx_th_tm_005fIf_005f2.doStartTag();
    if (_jspx_eval_tm_005fIf_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<td><input checked type='radio' id='male' name='gender' value='M'>Male\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f2);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f3 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f3.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f3.setParent(null);
    // /EmployeeAddForm.jsp(48,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f3.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${! employeeBean.male}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f3 = _jspx_th_tm_005fIf_005f3.doStartTag();
    if (_jspx_eval_tm_005fIf_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<td><input type='radio' id='male' name='gender' value='M'>Male\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f3);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f4 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f4.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f4.setParent(null);
    // /EmployeeAddForm.jsp(52,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f4.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.female}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f4 = _jspx_th_tm_005fIf_005f4.doStartTag();
    if (_jspx_eval_tm_005fIf_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<input checked type='radio' id='female' name='gender' value='F'>Female\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f4.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f4);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f5 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f5.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f5.setParent(null);
    // /EmployeeAddForm.jsp(55,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f5.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${! employeeBean.female}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f5 = _jspx_th_tm_005fIf_005f5.doStartTag();
    if (_jspx_eval_tm_005fIf_005f5 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<input type='radio' id='female' name='gender' value='F'>Female\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f5.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f5);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f6 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f6.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f6.setParent(null);
    // /EmployeeAddForm.jsp(64,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f6.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${employeeBean.indian}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f6 = _jspx_th_tm_005fIf_005f6.doStartTag();
    if (_jspx_eval_tm_005fIf_005f6 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<input checked type='checkbox' id='isIndian' name='isIndian' value='Y'>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f6.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f6);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f7(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f7 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f7.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f7.setParent(null);
    // /EmployeeAddForm.jsp(67,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f7.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${! employeeBean.indian}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f7 = _jspx_th_tm_005fIf_005f7.doStartTag();
    if (_jspx_eval_tm_005fIf_005f7 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<input type='checkbox' id='isIndian' name='isIndian' value='Y'>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f7.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f7);
    return false;
  }
}
