/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.6
 * Generated at: 2025-08-08 12:51:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class MasterPageTopSection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/mytags/tmtags.tld", Long.valueOf(1754657472219L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fGuard;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftm_005fGuard = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftm_005fGuard.release();
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fGuard_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang = 'en'>\r\n");
      out.write("<head>\r\n");
      out.write("<title>HR Application</title>\r\n");
      out.write("<link rel='stylesheet' type='text/css' href='/styletwo/css/styles.css'></link>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Main container starts here -->\r\n");
      out.write("<div class='main-container'>\r\n");
      out.write("<!-- Header container starts here -->\r\n");
      out.write("<div class='header-container'>\r\n");
      out.write("<img src='/styletwo/images/logo.png' class='logo'><div class='brand-name'>Thinking Machines</div>\r\n");
      out.write("<div class='user-panel'>\r\n");
      out.write("<u>Username</u>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='/styletwo/logout'>Logout</a><br>\r\n");
      out.write("<img src='/styletwo/images/user-icon.png' class='user-icon'>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div><!-- Header container ends here -->\r\n");
      out.write("<!-- content-section starts here -->\r\n");
      out.write("<div class='content'>\r\n");
      out.write("\r\n");
      out.write("<!-- left panel starts here -->\r\n");
      out.write("<div class='content-left-panel'>\r\n");
      out.write("\r\n");
      if (_jspx_meth_tm_005fIf_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fIf_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_tm_005fIf_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fIf_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_tm_005fIf_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!-- left panel ends here -->\r\n");
      out.write("\r\n");
      out.write("<div class='content-right-panel'><!-- right panel starts here -->\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tm_005fGuard_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:Guard
    com.thinking.machines.hr.tags.GuardTagHandler _jspx_th_tm_005fGuard_005f0 = (com.thinking.machines.hr.tags.GuardTagHandler) _005fjspx_005ftagPool_005ftm_005fGuard.get(com.thinking.machines.hr.tags.GuardTagHandler.class);
    _jspx_th_tm_005fGuard_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fGuard_005f0.setParent(null);
    int _jspx_eval_tm_005fGuard_005f0 = _jspx_th_tm_005fGuard_005f0.doStartTag();
    if (_jspx_eval_tm_005fGuard_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write('\r');
        out.write('\n');
        if (true) {
          _jspx_page_context.forward("/LoginForm.jsp");
          return true;
        }
        out.write('\r');
        out.write('\n');
        int evalDoAfterBody = _jspx_th_tm_005fGuard_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fGuard_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fGuard.reuse(_jspx_th_tm_005fGuard_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f0 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f0.setParent(null);
    // /MasterPageTopSection.jsp(31,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f0.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module==DESIGNATION}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f0 = _jspx_th_tm_005fIf_005f0.doStartTag();
    if (_jspx_eval_tm_005fIf_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<b>Designations</b><br>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f1 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f1.setParent(null);
    // /MasterPageTopSection.jsp(34,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f1.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module!=DESIGNATION}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f1 = _jspx_th_tm_005fIf_005f1.doStartTag();
    if (_jspx_eval_tm_005fIf_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<a href='/styletwo/Designations.jsp'>Designations</a><br>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f1);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f2 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f2.setParent(null);
    // /MasterPageTopSection.jsp(38,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f2.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module==EMPLOYEE}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f2 = _jspx_th_tm_005fIf_005f2.doStartTag();
    if (_jspx_eval_tm_005fIf_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<b>Employees</b><br><br>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f2);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f3 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f3.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f3.setParent(null);
    // /MasterPageTopSection.jsp(41,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f3.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module!=EMPLOYEE}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f3 = _jspx_th_tm_005fIf_005f3.doStartTag();
    if (_jspx_eval_tm_005fIf_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<a href='/styletwo/Employees.jsp'>Employees</a><br><br>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f3);
    return false;
  }

  private boolean _jspx_meth_tm_005fIf_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tm:If
    com.thinking.machines.hr.tags.IfTagHandler _jspx_th_tm_005fIf_005f4 = (com.thinking.machines.hr.tags.IfTagHandler) _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.get(com.thinking.machines.hr.tags.IfTagHandler.class);
    _jspx_th_tm_005fIf_005f4.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fIf_005f4.setParent(null);
    // /MasterPageTopSection.jsp(45,0) name = condition type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fIf_005f4.setCondition(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${module!=HOME}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_tm_005fIf_005f4 = _jspx_th_tm_005fIf_005f4.doStartTag();
    if (_jspx_eval_tm_005fIf_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("<a href='/styletwo/index.jsp'>Home</a><br>\r\n");
        int evalDoAfterBody = _jspx_th_tm_005fIf_005f4.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_tm_005fIf_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fIf_0026_005fcondition.reuse(_jspx_th_tm_005fIf_005f4);
    return false;
  }
}
