/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.6
 * Generated at: 2025-09-10 03:16:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class ConfirmDeleteEmployee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/mytags/tmtags.tld", Long.valueOf(1754657472219L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fModule_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function goToEmployeesView()\r\n");
      out.write("{\r\n");
      out.write("// below function submits a form which takes action to Employees.jsp\r\n");
      out.write("cancelEmployeeDeletion();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteEmployee()\r\n");
      out.write("{\r\n");
      out.write("var employeeId = document.getElementById('employeeId').value;\r\n");
      out.write("var dataToSend = \"employeeId=\" + encodeURI(employeeId)\r\n");
      out.write("\r\n");
      out.write("var xmlHttpRequest = new XMLHttpRequest();\r\n");
      out.write("xmlHttpRequest.onreadystatechange = function() {\r\n");
      out.write("if(this.readyState==4)\r\n");
      out.write("{\r\n");
      out.write("if(this.status==200)\r\n");
      out.write("{\r\n");
      out.write("var responseData = this.responseText;\r\n");
      out.write("responseData = JSON.parse(responseData);\r\n");
      out.write("if(responseData.success==true)\r\n");
      out.write("{\r\n");
      out.write("var employeeDeleteForm = document.getElementById('employeeDeleteForm');\r\n");
      out.write("employeeDeleteFormTable.style.display='none';	\r\n");
      out.write("var message = document.getElementById('message');\r\n");
      out.write("var deleteButton = document.getElementById('deleteButton');\r\n");
      out.write("var cancelButton = document.getElementById('cancelButton');\r\n");
      out.write("message.innerText = 'Employee deleted successfully.'\r\n");
      out.write("deleteButton.innerText = 'OK';\r\n");
      out.write("deleteButton.onclick = goToEmployeesView;\r\n");
      out.write("cancelButton.style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("else if(responseData.success==false)\r\n");
      out.write("{\r\n");
      out.write("//daoException in errorSection\r\n");
      out.write("errorSection.innerText = responseData.errorMessage;\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("{\r\n");
      out.write("alert('some problem');\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("};\r\n");
      out.write("xmlHttpRequest.open(\"POST\",\"employees/delete\",true);\r\n");
      out.write("xmlHttpRequest.setRequestHeader(\"Content-Type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("xmlHttpRequest.send(dataToSend);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function confirmDeleteEmployee()\r\n");
      out.write("{\r\n");
      out.write("var employeeId = new URLSearchParams(window.location.search).get('employeeId');	//creating object for parsing of search query. window is global variable, location represents current page's URL, search stands for search query - href would fetch entire query including http:// ...\r\n");
      out.write("var xmlHttpRequest = new XMLHttpRequest();\r\n");
      out.write("xmlHttpRequest.onreadystatechange = function() {\r\n");
      out.write("if(this.readyState==4)\r\n");
      out.write("{\r\n");
      out.write("if(this.status==200)\r\n");
      out.write("{\r\n");
      out.write("var responseData = this.responseText;\r\n");
      out.write("responseData = JSON.parse(responseData);\r\n");
      out.write("if(responseData.success==true)\r\n");
      out.write("{\r\n");
      out.write("document.getElementById('employeeId').value = responseData.data.employeeId;	//set hidden form field\r\n");
      out.write("document.getElementById('name').innerText = responseData.data.name;\r\n");
      out.write("document.getElementById('designationCode').innerText = responseData.data.title;	//splits[4] contains designation 'title'. splits[3] contains designation 'code'\r\n");
      out.write("document.getElementById('dateOfBirth').innerText = responseData.data.dateOfBirth;\r\n");
      out.write("document.getElementById('gender').innerText = (responseData.data.gender == 'M')?'Male':'Female'\r\n");
      out.write("document.getElementById('isIndian').innerText = (responseData.data.isIndian==true)?'Indian':'Not Indian';			//returns true/false\r\n");
      out.write("document.getElementById('basicSalary').innerText = responseData.data.basicSalary;\r\n");
      out.write("document.getElementById('panNumber').innerText = responseData.data.panNumber;\r\n");
      out.write("document.getElementById('aadharCardNumber').innerText = responseData.data.aadharCardNumber;\r\n");
      out.write("}\r\n");
      out.write("else if(responseData.success==false) //means user manually typed incorrect code in search bar. Redirect to Employees.jsp page w/o further encouragement\r\n");
      out.write("{\r\n");
      out.write("window.location.href = 'Employees.jsp';\r\n");
      out.write("}\r\n");
      out.write("else \r\n");
      out.write("{\r\n");
      out.write("alert('some problem');\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("};\r\n");
      out.write("var requestURL = 'employees/getByEmployeeId?employeeId=' + encodeURI(employeeId);\r\n");
      out.write("xmlHttpRequest.open('GET',requestURL,true);\r\n");
      out.write("xmlHttpRequest.send();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("window.addEventListener('load',confirmDeleteEmployee);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/MasterPageTopSection.jsp", out, false);
      out.write("\r\n");
      out.write("<script src='/stylethree/js/ConfirmDeleteEmployee.js'></script>\r\n");
      out.write("<h2>Employee (Delete Module)</h2><br>\r\n");
      out.write("<form id='employeeDeleteForm'>\r\n");
      if (_jspx_meth_tm_005fFormId_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<input type='hidden' id='employeeId' name='employeeId' value=''>\r\n");
      out.write("<span id = 'message'>Are you sure you want to delete employee?</span><br><br>\r\n");
      out.write("<table id='employeeDeleteFormTable'>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Name:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='name' name='name'></span></b>\r\n");
      out.write("<span id='nameErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Designation:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='designationCode' name='designationCode'></span></b>\r\n");
      out.write("<span id='designationCodeErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Date of birth:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='dateOfBirth' name='dateOfBirth'></span></b>\r\n");
      out.write("<span id='dateOfBirthErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Gender:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='gender' name='gender'></span></b>\r\n");
      out.write("<span id='genderErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Indian?</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='isIndian' name='isIndian'></span></b>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<span id='isIndianErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Basic salary:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='basicSalary' name='basicSalary'></span></b>\r\n");
      out.write("<span id='basicSalaryErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>PAN number:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='panNumber' name='panNumber'></span></b>\r\n");
      out.write("<span id='panNumberErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Aadhar Card Number:</td>\r\n");
      out.write("<td>\r\n");
      out.write("<b><span id='aadharCardNumber' name='aadharCardNumber'></span></b>\r\n");
      out.write("<span id='aadharCardNumberErrorSection' style='color:red'></span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<span id='errorSection' style='color:red'></span>\r\n");
      out.write("<br><br>\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button type='button' id='deleteButton' onclick='deleteEmployee()'>Delete</button>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button type='button' id='cancelButton' onclick='cancelEmployeeDeletion()'>Cancel</button>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<form action='/stylethree/Employees.jsp' id='cancelEmployeeDeletionForm'>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/MasterPageBottomSection.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tm_005fModule_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  tm:Module
    com.thinking.machines.hr.tags.ModuleTagHandler _jspx_th_tm_005fModule_005f0 = (com.thinking.machines.hr.tags.ModuleTagHandler) _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.get(com.thinking.machines.hr.tags.ModuleTagHandler.class);
    _jspx_th_tm_005fModule_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fModule_005f0.setParent(null);
    // /ConfirmDeleteEmployee.jsp(2,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fModule_005f0.setName("EMPLOYEE");
    int _jspx_eval_tm_005fModule_005f0 = _jspx_th_tm_005fModule_005f0.doStartTag();
    if (_jspx_th_tm_005fModule_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.reuse(_jspx_th_tm_005fModule_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fFormId_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  tm:FormId
    com.thinking.machines.hr.tags.FormIdTagHandler _jspx_th_tm_005fFormId_005f0 = (com.thinking.machines.hr.tags.FormIdTagHandler) _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.get(com.thinking.machines.hr.tags.FormIdTagHandler.class);
    _jspx_th_tm_005fFormId_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fFormId_005f0.setParent(null);
    int _jspx_eval_tm_005fFormId_005f0 = _jspx_th_tm_005fFormId_005f0.doStartTag();
    if (_jspx_th_tm_005fFormId_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.reuse(_jspx_th_tm_005fFormId_005f0);
    return false;
  }
}
