/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.6
 * Generated at: 2025-09-08 13:42:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class DesignationAddForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/mytags/tmtags.tld", Long.valueOf(1754657472219L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_tm_005fModule_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/MasterPageTopSection.jsp", out, false);
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function addAnotherDesignation()\r\n");
      out.write("{\r\n");
      out.write("var message = document.getElementById('message');\r\n");
      out.write("var addButton = document.getElementById('addButton');\r\n");
      out.write("var cancelButton = document.getElementById('cancelButton');\r\n");
      out.write("message.innerHTML = 'Designation'\r\n");
      out.write("addButton.innerText = 'Add';\r\n");
      out.write("addButton.onclick = addDesignation;\r\n");
      out.write("cancelButton.innerText = 'Cancel';\r\n");
      out.write("var titleInputField = document.createElement(\"input\"); \r\n");
      out.write("titleInputField.type = 'text';\r\n");
      out.write("titleInputField.id = 'title'; \r\n");
      out.write("titleInputField.name = 'title';\r\n");
      out.write("titleInputField.maxlength = 35;\r\n");
      out.write("titleInputField.size = 36;\r\n");
      out.write("message.after(titleInputField);		// adding a new generated input\r\n");
      out.write("}\r\n");
      out.write("function addDesignation()\r\n");
      out.write("{\r\n");
      out.write("var designationAddForm = document.getElementById('designationAddForm');\r\n");
      out.write("if(validateForm(designationAddForm)==false)\r\n");
      out.write("{\r\n");
      out.write("return;\r\n");
      out.write("}\r\n");
      out.write("//if control reaches here means form is valid at a basic level\r\n");
      out.write("var title = document.getElementById('title').value;\r\n");
      out.write("var formId = document.getElementById('formId').value;\r\n");
      out.write("var dataToSend = 'formId=' + encodeURI(formId);\r\n");
      out.write("var dataToSend = dataToSend + '&title=' + encodeURI(title);\r\n");
      out.write("var xmlHttpRequest = new XMLHttpRequest();\r\n");
      out.write("xmlHttpRequest.onreadystatechange = function() {\r\n");
      out.write("if(this.readyState==4)\r\n");
      out.write("{\r\n");
      out.write("if(this.status==200)\r\n");
      out.write("{\r\n");
      out.write("var responseData = this.responseText;\r\n");
      out.write("responseData = JSON.parse(responseData);\r\n");
      out.write("if(responseData.success==true)	//means successfully added\r\n");
      out.write("{\r\n");
      out.write("var titleErrorSection = document.getElementById('titleErrorSection');\r\n");
      out.write("titleErrorSection.innerHTML = '';\r\n");
      out.write("var message = document.getElementById('message');\r\n");
      out.write("var addButton = document.getElementById('addButton');\r\n");
      out.write("var cancelButton = document.getElementById('cancelButton');\r\n");
      out.write("var titleInputField = document.getElementById('title').remove();\r\n");
      out.write("message.innerText = 'Designation added. Add more?'\r\n");
      out.write("addButton.innerText = 'Yes';\r\n");
      out.write("addButton.onclick = addAnotherDesignation;\r\n");
      out.write("cancelButton.innerText = 'No';\r\n");
      out.write("}\r\n");
      out.write("else if(responseData.success==false) //means not added. Show error.\r\n");
      out.write("{\r\n");
      out.write("var titleErrorSection = document.getElementById('titleErrorSection');\r\n");
      out.write("titleErrorSection.innerHTML = responseData.errorMessage;\r\n");
      out.write("}\r\n");
      out.write("else alert('some problem');\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("};\r\n");
      out.write("xmlHttpRequest.open('POST','designations/add',true);\r\n");
      out.write("xmlHttpRequest.setRequestHeader('Content-Type','application/x-www-form-urlencoded');\r\n");
      out.write("xmlHttpRequest.send(dataToSend);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src='/stylethree/js/DesignationAddForm.js'></script>\r\n");
      out.write("<h2>Designation (Add Module)</h2>\r\n");
      out.write("<br>\r\n");
      out.write("<form id='designationAddForm'>\r\n");
      if (_jspx_meth_tm_005fFormId_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<span id = 'message'>Designation</span>\r\n");
      out.write("<input type='text' id='title' name='title' maxlength='35' size='36'>\r\n");
      out.write("<span class='error' id='titleErrorSection'>\r\n");
      out.write("</span><br><br>\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button type='button' onclick='addDesignation()' id='addButton'>Add</button>\r\n");
      out.write("</form>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("<button type='button' id='cancelButton' onclick='cancelAddition()'>Cancel</button>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<form action='/stylethree/Designations.jsp' id='cancelDesignationAdditionForm'>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/MasterPageBottomSection.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tm_005fModule_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  tm:Module
    com.thinking.machines.hr.tags.ModuleTagHandler _jspx_th_tm_005fModule_005f0 = (com.thinking.machines.hr.tags.ModuleTagHandler) _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.get(com.thinking.machines.hr.tags.ModuleTagHandler.class);
    _jspx_th_tm_005fModule_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fModule_005f0.setParent(null);
    // /DesignationAddForm.jsp(2,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tm_005fModule_005f0.setName("DESIGNATION");
    int _jspx_eval_tm_005fModule_005f0 = _jspx_th_tm_005fModule_005f0.doStartTag();
    if (_jspx_th_tm_005fModule_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fModule_0026_005fname_005fnobody.reuse(_jspx_th_tm_005fModule_005f0);
    return false;
  }

  private boolean _jspx_meth_tm_005fFormId_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  tm:FormId
    com.thinking.machines.hr.tags.FormIdTagHandler _jspx_th_tm_005fFormId_005f0 = (com.thinking.machines.hr.tags.FormIdTagHandler) _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.get(com.thinking.machines.hr.tags.FormIdTagHandler.class);
    _jspx_th_tm_005fFormId_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tm_005fFormId_005f0.setParent(null);
    int _jspx_eval_tm_005fFormId_005f0 = _jspx_th_tm_005fFormId_005f0.doStartTag();
    if (_jspx_th_tm_005fFormId_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ftm_005fFormId_005fnobody.reuse(_jspx_th_tm_005fFormId_005f0);
    return false;
  }
}
