/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.6
 * Generated at: 2025-08-18 07:16:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class LoginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      com.thinking.machines.hr.beans.ErrorBean errorBean = null;
      errorBean = (com.thinking.machines.hr.beans.ErrorBean) _jspx_page_context.getAttribute("errorBean", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (errorBean == null){
        errorBean = new com.thinking.machines.hr.beans.ErrorBean();
        _jspx_page_context.setAttribute("errorBean", errorBean, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang = 'en'>\r\n");
      out.write("<head>\r\n");
      out.write("<title>HR Application</title>\r\n");
      out.write("<link rel='stylesheet' type='text/css' href='/styletwo/css/loginFormStyles.css'></link>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Main container starts here -->\r\n");
      out.write("<div class='main-container'>\r\n");
      out.write("<!-- Header container starts here -->\r\n");
      out.write("<div class='header-container'>\r\n");
      out.write("<img src='/styletwo/images/logo.png' class='logo'><div class='brand-name'>Thinking Machines</div>\r\n");
      out.write("</div><!-- Header container ends here -->\r\n");
      out.write("<!-- content-section starts here -->\r\n");
      out.write("<div class='content'>\r\n");
      out.write("\r\n");
      out.write("<div class='content-panel'><!-- content panel starts here -->\r\n");
      out.write("\r\n");
      out.write("<! -- Panel title starts here -->\r\n");
      out.write("<span class='login-panel-title'>\r\n");
      out.write("Administrator\r\n");
      out.write("</span>\r\n");
      out.write("<! -- Panel title ends here -->\r\n");
      out.write("<! -- Login section starts here -->\r\n");
      out.write("<div class='login-module'>\r\n");
      out.write("<span class='error' id='loginErrorSection'>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorBean.error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("</span>\r\n");
      out.write("<form method='post' action='Login.jsp' >\r\n");
      out.write("Username: <input type='text' id='username' name='username' placeholder='Username' maxlength='15' required><br><br>\r\n");
      out.write("Password: <input type='password' id='password' name='password' placeholder='Password' maxlength='15' required><br><br>\r\n");
      out.write("<button type='submit' class='login-button'>Login </button>\r\n");
      out.write("\r\n");
      out.write("</form>	\r\n");
      out.write("</div>\r\n");
      out.write("<! -- Login section ends here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!-- content panel ends here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer starts here -->\r\n");
      out.write("<div class='footer'>\r\n");
      out.write("&copy; Thinking Machines 2025\r\n");
      out.write("</div> <!-- footer ends here -->\r\n");
      out.write("</div> <!-- Main container ends here -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
